version: "3"

volumes:
  {{ cookiecutter.app_name }}-postgres-data:

services:
  {{ cookiecutter.app_name }}-postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      APP_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      MIGRATOR_PASSWORD: postgres
    volumes:
      - ./docker/{{ cookiecutter.app_name }}-postgres/init:/docker-entrypoint-initdb.d/
      - {{ cookiecutter.app_name }}-postgres-data:/var/lib/postgresql/data

  {{ cookiecutter.app_name }}-client:
    build:
      context: .
      dockerfile: ./docker/{{ cookiecutter.app_name }}-client/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules

  {{ cookiecutter.app_name }}-server:
    build:
      context: .
      dockerfile: ./docker/{{ cookiecutter.app_name }}-server/Dockerfile
      {% if cookiecutter.use_devcontainers == 'Yes' %}args:
        - DEV_CONTAINERS=1
        - DEV_NODE_VERSION={{ cookiecutter.__node_version }}{% endif %}
    depends_on:
      - {{ cookiecutter.app_name }}-postgres
    environment:
      FLASK_APP: {{ cookiecutter.app_name }}
      APP_ENVIRONMENT: dev
      PGPASSWORD: postgres
      APP_PASSWORD: postgres
      MIGRATOR_PASSWORD: postgres
    ports:
      - 5000:5000
    volumes:
      - .:/app
      {% if cookiecutter.use_devcontainers == 'Yes' %}- /app/node_modules{% endif %}
