name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv==2021.11.15
          pipenv sync --dev

      - name: Run Tests
        run: bash tests/integration.sh
